name: Publish Release

on:
  workflow_run:
    workflows: [ "Publish Conan branch package" ]
    branches: [ main ]
    types:
      - completed


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-conan-branch-package:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@feature/initial_version
    with:
      config-path: .github/common-workflow-config.yml
    secrets:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PW: ${{ secrets.CONAN_PW }}
