name: Publish Release for Tag

on:
  create:

concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-conan-branch-package:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@develop
    with:
      public_artifactory: true
      os: ubuntu-22.04
      compiler: clang-16
      cmake-version: 3.22.6
      conan-version: 2.0.13
      use-tag: true
    secrets:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PW: ${{ secrets.CONAN_PW }}
